# Generated by Django 4.0.2 on 2023-07-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NataliyaApp', '0002_category_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='role',
            field=models.CharField(blank=True, choices=[('user1', 'Staff'), ('user2', 'User')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
