# Generated by Django 4.0.2 on 2023-07-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NataliyaApp', '0003_alter_user_registration_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(default='static/images/default.png', upload_to='images/category-banner'),
        ),
    ]
