# Generated by Django 4.0.2 on 2023-07-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NataliyaApp', '0004_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='title_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
