# Generated by Django 4.0.2 on 2023-08-10 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NataliyaApp', '0006_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='bannerads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image1', models.FileField(blank=True, null=True, upload_to='images/banner')),
                ('banner_image2', models.FileField(blank=True, null=True, upload_to='images/banner')),
                ('banner_image3', models.FileField(blank=True, null=True, upload_to='images/banner')),
                ('banner_image4', models.FileField(blank=True, null=True, upload_to='images/banner')),
                ('banner_image5', models.FileField(blank=True, null=True, upload_to='images/banner')),
                ('banner_title1', models.CharField(blank=True, max_length=255, null=True)),
                ('banner_title2', models.CharField(blank=True, max_length=255, null=True)),
                ('banner_title3', models.CharField(blank=True, max_length=255, null=True)),
                ('banner_title4', models.CharField(blank=True, max_length=255, null=True)),
                ('banner_title5', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(blank=True, default=0, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='rating',
        ),
        migrations.AddField(
            model_name='item',
            name='offer_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='under_category',
            field=models.CharField(blank=True, choices=[('Home Appliance', 'Home Appliance'), ('Electronics', 'Electronics'), ('Furniture', 'Furniture')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile_user',
            name='joindate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='otp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(default='static/images/logo/noimage.jpg', upload_to='images/category-banner'),
        ),
        migrations.AlterField(
            model_name='item',
            name='buying_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NataliyaApp.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(default='static/images/logo/noimage.jpg', upload_to='images/items'),
        ),
        migrations.AlterField(
            model_name='item',
            name='offer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile_user',
            name='pro_pic',
            field=models.ImageField(default='static/images/logo/icon.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='status',
            field=models.CharField(blank=True, default='active', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='offer_zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default='static/images/logo/noimage.jpg', upload_to='images/items')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('price', models.FloatField(default=0)),
                ('offer_price', models.FloatField(default=0)),
                ('offer', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NataliyaApp.user_registration')),
            ],
        ),
        migrations.CreateModel(
            name='checkout_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('item_price', models.FloatField(blank=True, null=True)),
                ('checkout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NataliyaApp.checkout')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NataliyaApp.item')),
            ],
        ),
        migrations.AddField(
            model_name='checkout',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NataliyaApp.profile_user'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NataliyaApp.user_registration'),
        ),
    ]
