# Generated by Django 4.0.2 on 2023-08-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NataliyaApp', '0007_bannerads_checkout_remove_item_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile_user',
            name='banner_access',
            field=models.CharField(blank=True, default='false', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile_user',
            name='cat_access',
            field=models.CharField(blank=True, default='false', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile_user',
            name='item_access',
            field=models.CharField(blank=True, default='false', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile_user',
            name='offer_access',
            field=models.CharField(blank=True, default='false', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile_user',
            name='order_access',
            field=models.CharField(blank=True, default='false', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile_user',
            name='user_access',
            field=models.CharField(blank=True, default='false', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='under_category',
            field=models.CharField(blank=True, choices=[('Ice Cream', 'Ice Cream'), ('Wrap', 'Wrap')], max_length=255, null=True),
        ),
    ]
